### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by NotSoMik** [Rahuletto/simply-xp#7]
Hello, I also said it in your [other repository](https://github.com/Abadima/simply-xp-test/issues/1#issuecomment-1218066256), with the new version I got this
![Screenshot_20220818-111140_Chrome](https://user-images.githubusercontent.com/74645196/185358305-ba54e3fa-3eb9-4d4c-9a49-d2ae435a1f26.jpg)

**Comment by NotSoMik** [comment]
Since this is the official repository I thought it would be more correct to report the issues here

**Comment by Abadima** [comment]
Not a bug, 
![image](https://user-images.githubusercontent.com/39747270/185746004-aa48e24a-73e3-45e7-b602-e0be7b37d2c7.png)
Roles (by default) only show if they are given to the user, with the new bug fix I added, it turns it into an array, so you might want to adjust that to something like 
```js
for (var i = 0; i < role.length; i++) {
   str += `<@&{role[i].role}>`
}
``` 
Since with multiple roles, it can log an "array", which means "role.role" won't really do much.
*TIP: You should also check the length, as it will return `[]` if no roles were given.
Hope this helps! Let me know if there are any further issues.
